Group support for AsyncPatientSource
projecttacoma/cql-exec-fhir pull request #7
Opened 2022-04-26 14:19 UTC by sarahmcdougall

# Summary
Adds support for a Group reference to be used for populating patient Ids for the AsyncPatientSource class.

## New behavior
Rather than taking in a list of patient Ids to use in `currentPatient()`, the user can now specify the id of a Group resource. The patient Ids referenced in the Group resource are used to create`AsyncPatient` instances.

## Code changes
* New function in the AsyncPatientSource class called `loadGroupId()` that grabs the patient Ids referenced in the Group resource and populates the `patientIds` array
* Added unit testing for Group support, which creates a test Group resource that references test patients

# Testing guidance
* Run the unit tests with `yarn run test`
* To test with `fqm-execution`, see [the corresponding PR in fqm-execution](https://github.com/projecttacoma/fqm-execution/pull/123). From fqm-execution, link to this cql-exec-fhir branch and follow the testing guidance listed in the fqm-execution PR.

2022-04-27 14:40 UTC, natjoe4 requested changes
Nice work, just one small comment. Also... maybe even too small to be considered a nitpick, but you spell id with a capital I in a couple places in this PR, and with a lowercase i elsewhere. If you have extra time, you could change them all to lowercase.

2022-04-27 14:40 UTC, natjoe4 commented on test/r401_test.js
> +  it('throws correct error when specified group Id cannot be found on the server', async () => {
For this test, I think we still need to use nock to mock out the request. Right now this catch statement gets hit because Nock throws a "No match for request" error. Could even get fancy and have it return an error message that gets incorporated into the expect statement.

2022-04-27 19:22 UTC, sarahmcdougall commented on test/r401_test.js
> +  it('throws correct error when specified group Id cannot be found on the server', async () => {
I incorporated nock into the test to mock out the request - let me know if the changes match what you were thinking.

2022-04-28 14:20 UTC, natjoe4 approved these changes
Nice work!

2022-04-28 14:21 UTC, merged